"""initial database setup

Revision ID: 6ea04d361463
Revises: 
Create Date: 2025-06-05 16:15:18.388490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea04d361463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('gdp_growth', sa.Float(), nullable=False),
    sa.Column('gdp_per_capita', sa.Float(), nullable=True),
    sa.Column('inflation_rate', sa.Float(), nullable=False),
    sa.Column('food_inflation', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('industrial_production', sa.Float(), nullable=True),
    sa.Column('agricultural_production', sa.Float(), nullable=True),
    sa.Column('exports', sa.Float(), nullable=True),
    sa.Column('imports', sa.Float(), nullable=True),
    sa.Column('trade_balance', sa.Float(), nullable=True),
    sa.Column('current_account_balance', sa.Float(), nullable=True),
    sa.Column('fdi_inflow', sa.Float(), nullable=True),
    sa.Column('remittances', sa.Float(), nullable=True),
    sa.Column('fx_reserves', sa.Float(), nullable=True),
    sa.Column('etb_usd', sa.Float(), nullable=False),
    sa.Column('etb_eur', sa.Float(), nullable=False),
    sa.Column('etb_gbp', sa.Float(), nullable=False),
    sa.Column('etb_jpy', sa.Float(), nullable=False),
    sa.Column('etb_cny', sa.Float(), nullable=True),
    sa.Column('govt_revenue', sa.Float(), nullable=True),
    sa.Column('govt_expenditure', sa.Float(), nullable=True),
    sa.Column('budget_deficit', sa.Float(), nullable=True),
    sa.Column('govt_debt', sa.Float(), nullable=True),
    sa.Column('tax_revenue', sa.Float(), nullable=True),
    sa.Column('total_deposits', sa.Float(), nullable=True),
    sa.Column('total_loans', sa.Float(), nullable=True),
    sa.Column('npl_ratio', sa.Float(), nullable=True),
    sa.Column('loan_to_deposit', sa.Float(), nullable=True),
    sa.Column('money_supply_m1', sa.Float(), nullable=True),
    sa.Column('money_supply_m2', sa.Float(), nullable=True),
    sa.Column('private_sector_credit', sa.Float(), nullable=True),
    sa.Column('coffee_price', sa.Float(), nullable=True),
    sa.Column('gold_price', sa.Float(), nullable=True),
    sa.Column('oil_price', sa.Float(), nullable=True),
    sa.Column('wheat_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('company_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_of_revenue', sa.Float(), nullable=True),
    sa.Column('gross_profit', sa.Float(), nullable=True),
    sa.Column('operating_expenses', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.Float(), nullable=True),
    sa.Column('interest_expense', sa.Float(), nullable=True),
    sa.Column('profit_before_tax', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Float(), nullable=True),
    sa.Column('cash_equivalents', sa.Float(), nullable=True),
    sa.Column('accounts_receivable', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Float(), nullable=True),
    sa.Column('total_current_assets', sa.Float(), nullable=True),
    sa.Column('fixed_assets', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('accounts_payable', sa.Float(), nullable=True),
    sa.Column('short_term_debt', sa.Float(), nullable=True),
    sa.Column('total_current_liabilities', sa.Float(), nullable=True),
    sa.Column('long_term_debt', sa.Float(), nullable=True),
    sa.Column('total_liabilities', sa.Float(), nullable=True),
    sa.Column('total_equity', sa.Float(), nullable=True),
    sa.Column('operating_cash_flow', sa.Float(), nullable=True),
    sa.Column('investing_cash_flow', sa.Float(), nullable=True),
    sa.Column('financing_cash_flow', sa.Float(), nullable=True),
    sa.Column('net_cash_flow', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('return_on_assets', sa.Float(), nullable=True),
    sa.Column('profit_margin', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('financials')
    op.drop_table('company_news')
    op.drop_table('user')
    op.drop_table('macro_indicators')
    op.drop_table('company')
    # ### end Alembic commands ###
